# Generated by Django 5.0.3 on 2024-03-21 05:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Olxapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='list_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='price',
            field=models.CharField(max_length=50),
        ),
    ]
