# Generated by Django 5.0.3 on 2024-03-21 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Olxapp', '0003_category_alter_recipe_list_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Olxapp.category'),
        ),
    ]
