# Generated by Django 5.0.3 on 2024-03-22 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Olxapp', '0005_alter_category_options_alter_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe_des',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='price',
            new_name='SET_A_PRICE',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe_image',
            new_name='Upload_image',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe_name',
            new_name='title',
        ),
    ]
